name: Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r vehicle/requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest

    - name: Create envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        file_name: .env
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Deploy if tests pass
      if: success()
      run: |
        npm install -g serverless@3.38.0
        npm install -g serverless-dotenv-plugin
        npm install dotenv
        sls deploy --verbose --param="audienceIssuerUrl=${{ secrets.AUDIENCE_ISSUER_URL }}" --param="audienceClientId=${{ secrets.AUDIENCE_CLIENT_ID }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        AUDIENCE_ISSUER_URL: ${{ secrets.AUDIENCE_ISSUER_URL }}
        AUDIENCE_CLIENT_ID: ${{ secrets.AUDIENCE_CLIENT_ID }}

    - name: Clean up .env file
      if: success()
      run: rm .env
